### ISSUE TITLE
Todo Before Submission

### ISSUE THREAD

**Issue by harriet-mason** [harriet-mason/paper-cassowaryr#5]
- [ ] PDF is not knitting for me (maybe get someone else to knit it on their computer?) HTML works fine though
- [ ]  Stuart is listed as an author. I don't know his current affiliation. Does he need to read the paper?
- [ ] Need to resubmit carrowaryr to CRAN (but do all the propper checks which I forgot to do)
